# Generated by Django 4.1 on 2022-08-21 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('fechanacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('telefono', models.IntegerField(verbose_name='telefono')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'db_table': 'cliente',
            },
        ),
    ]